Task_2_2. Tree
PeachMood/OOP pull request #5
Opened 2021-12-15 16:52 UTC by PeachMood

2021-12-15 16:58 UTC, PeachMood commented
К сожалению, до мягкого дедлайна не удалось много написать, потому что возникли проблемы с gradle и на их решение пришлось потратить много времени. К жесткому дедлайну обязательно улучшу реализацию, добавлю методы и исправлю ошибки)

2021-12-17 11:24 UTC, Leidenn2509 requested changes
- javadoc
- tests. Посмотрите пример из условия задачи. Не забудьте про возможность получить поддерево

2021-12-17 11:24 UTC, Leidenn2509 commented on Task_2_2/src/main/java/ru/nsu/voronova/Tree.java
> +    @SuppressWarnings("unchecked")
Что-то с этим делать нужно. Злоумышлинники могут передать вам сюда всё что угодно

2021-12-24 16:52 UTC, PeachMood commented
Javadoc будет к воскресенью

2021-12-24 19:11 UTC, Leidenn2509 commented
Всё отлично. Жду javadoc и зачту лабу

2021-12-24 19:12 UTC, Leidenn2509 requested changes
- javadoc

2021-12-25 17:58 UTC, Leidenn2509 approved these changes

2021-12-25 17:58 UTC, merged