Task_2_1_1. Prime numbers
PeachMood/OOP pull request #6
Opened 2022-02-16 11:12 UTC by PeachMood

2022-02-18 09:07 UTC, PeachMood commented
Судя по получившемуся графику, решение с трэдами у меня работает медленнее всего :)
Вот и не ясно: так и должно быть, или решение нужно переписывать...

2022-02-21 09:03 UTC, Leidenn2509 commented
- Вы немного напутали задачу, нужно понять есть ли в коллекции не простое число
- У вас всё работает правильно, просто вы дали недостаточную наргрузку на алгоритм. С 20 и 7 конечно последовательно будет очень быстро, у вас цикл в `isPrime` сделает 1-2 итерации только. Я поменял числа на 1048561 (911 * 1151) и 1048571, и так же поместил простое число в самый конец коллекции. Это увеличило нагрузку и я получил следующий график
![image](https://i.imgur.com/aEAzQAB.png)

2022-02-21 09:03 UTC, Leidenn2509 requested changes

2022-02-21 09:06 UTC, Leidenn2509 requested changes

2022-02-21 09:06 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/voronova/ThreadPrimeSearch.java
> +        Deque<Integer> deque = new ArrayDeque<>(numberList);
They are not thread-safe; in the absence of external synchronization, they do not support concurrent access by multiple threads.

2022-02-24 12:37 UTC, Leidenn2509 requested changes

2022-02-24 12:37 UTC, Leidenn2509 commented on Task_2_1_1/src/test/java/ru/nsu/voronova/unitTest/ThreadNotPrimeSearchTest.java
> +    public void search_largeData1() throws ExecutionException, InterruptedException {
`expected: <false> but was: <true>`

2022-02-24 12:50 UTC, PeachMood commented on Task_2_1_1/src/test/java/ru/nsu/voronova/unitTest/ThreadNotPrimeSearchTest.java
> +    public void search_largeData1() throws ExecutionException, InterruptedException {
Думала, что заполнила массив простыми числами, а оказалось, что это не простые числа. Исправила)

2022-02-25 17:44 UTC, Leidenn2509 approved these changes

2022-02-25 17:44 UTC, merged