Task_2_1_2. Pizzeria
PeachMood/OOP pull request #7
Opened 2022-03-14 03:30 UTC by PeachMood

2022-03-14 19:12 UTC, PeachMood commented
Извините, пожалуйста, забыла вас назначить ревьюером((

2022-03-22 09:44 UTC, Leidenn2509 requested changes

2022-03-22 09:44 UTC, Leidenn2509 commented on Task_2_1_2/src/main/java/ru/nsu/voronova/QueueBlocking.java
> +        while (dequeue.size() < 1) {
isEmpty

2022-03-22 09:44 UTC, Leidenn2509 commented on Task_2_1_2/src/main/java/ru/nsu/voronova/Courier.java
> +        List<Order> orders = storage.get(bagCapacity);
По условию курьер не должен ждать на складе. Просто взять сколько может и всё

2022-03-29 10:59 UTC, Leidenn2509 approved these changes

2022-04-03 14:12 UTC, merged