Task_2_1_4. Domain-Specific Languages
PeachMood/OOP pull request #9
Opened 2022-06-05 09:21 UTC by PeachMood

2022-06-05 09:30 UTC, PeachMood commented
В файле Main.kt можно найти пример использования модели DSL. На данный момент существует несколько проблем:
1) Не добавлены маркеры
2) Свойства одних объектов (например, attendance у lesson) зависят от наличия других объектов (например, списка студентов). Другими словами, если сначала прописать lessons, а потом students, то attendance у каждого lesson будет представлять собой пустой массив. Можно ли оставить так?
3) Я первый раз пишу на котлине, так что возможны проблемы со стилем кода. Особенно я пока плохо понимаю, нужно ли следовать концепции ООП при написании классов на котлине. Во примерах для Builder классов поля класса делались публичными

2022-06-07 12:00 UTC, Leidenn2509 requested changes

2022-06-07 12:01 UTC, Leidenn2509 commented
По поводу 2. В идеале конечно хочется, чтобы модель сначала создавалась, а потом анализировалась. Т.е. была возможность указать атенди студентов в начале, а самих студентов добавить потом когда-нибудь. Но это требование необязательное

2022-06-14 18:40 UTC, PeachMood commented
Если что-то нужно исправить, я сделаю, только, пожалуйста, не заставляйте писать доки. Я не выдержу снова писать их для 20+ классов...
Надеюсь на ваше понимание)

2022-06-15 15:36 UTC, alradish requested changes
С кодом что-то не то. В некоторых местах испольуются классы которых не существует.
Приложите ещё пример конфига и отчёта

2022-06-15 15:56 UTC, PeachMood commented
Для отображения результатов тестирования и документации я использую html странички, сгенерированные gradle для каждого репозитория, поэтому если открывать эти страницы изолированно от репозиториев, то ссылки никуда не будут приводить

2022-06-15 16:18 UTC, Leidenn2509 approved these changes

2023-06-10 18:09 UTC, merged